# Generated by Django 3.1.3 on 2020-12-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201211_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=256)),
                ('website_link', models.CharField(max_length=500, null=True)),
                ('repository_link', models.CharField(max_length=500, null=True)),
                ('post_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='discorduser',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
