# Generated by Django 3.0.1 on 2020-12-17 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_project_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
