# Generated by Django 3.0.1 on 2020-12-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_project_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='repository_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='website_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
