# Generated by Django 3.0.1 on 2020-12-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_project_author_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_views',
            field=models.IntegerField(default=0),
        ),
    ]
