# Generated by Django 3.0.1 on 2020-12-17 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_project_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='likes',
        ),
    ]
